### ISSUE TITLE
Collaborators graph not displayed properly when microservice is down

### ISSUE THREAD

**Issue by OlgaMaciaszek** [4finance/micro-infra-spring#476] opened 2015-07-17 12:53 UTC
Having the following result on `/collaborators/all`
```json
{"com/blogspot/toomuchcoding/fraudDetectionService":{"http://localhost:13974":{"status":"DOWN","collaborators":{}}},"com/blogspot/toomuchcoding/loanApplicationService":{"http://192.168.173.73:8080":{"status":"UP","collaborators":{"com/blogspot/toomuchcoding/fraudDetectionService":{"http://localhost:13974":"DOWN"}}}}}
```
with a microservice that is down, we get:
`c.o.i.healthcheck.PingClient: Unable to ping service [http://localhost:11492]!`

which causes an exception screen to be displayed on `collaborators/view.html` - the graph is not being dislayed at all.
![graph1](https://cloud.githubusercontent.com/assets/4328892/8747452/839bbd5e-2c93-11e5-8992-ae03b9da4175.png)
![graph2](https://cloud.githubusercontent.com/assets/4328892/8747453/839eeaa6-2c93-11e5-8c23-e687921fe9c9.png)

Checked on v 0.9.1.

**Comment by marcingrzejszczak** [comment] 2015-07-24 23:14
@nurkiewicz have you seen this already?

**Comment by marcingrzejszczak** [comment] 2015-11-15 11:38
@nurkiewicz ping :)

**Comment by nurkiewicz** [comment] 2015-11-15 13:02
I couldn't reproduce it. In fact view.html is just a static HTML file + a
bunch of JavaScript so it's virtually impossible that it triggers Spring
MVC error. HTML is loaded first and JSON with collaborators later. I
believe this was misconfiguration, unrelated to one of the services being
down.

2015-11-15 12:38 GMT+01:00 Marcin Grzejszczak <notifications@github.com>:

> @nurkiewicz <https://github.com/nurkiewicz> ping :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4finance/micro-infra-spring/issues/476#issuecomment-156805953>
> .
>



-- 
Tomasz Nurkiewicz
http://nurkiewicz.com

**Comment by marcingrzejszczak** [comment] 2015-11-15 13:41
So let's close it then...

**Closed by marcingrzejszczak** 2015-11-15 13:41 UTC
