### ISSUE TITLE
install task not working

### ISSUE THREAD

**Issue by ArturGajowy** [4finance/micro-infra-spring#454] opened 2015-06-18 14:45 UTC
```
artur@artur-HP-ZBook-15 ~/projects/micro-infra-spring $ ./gradlew install
Parallel execution is an incubating feature.
Trying to parse the project arguments
:addHashFile
:stub-runner:stub-runner:processResources
:micro-deps:micro-deps:compileJava UP-TO-DATE
:addHashFile UP-TO-DATE
:micro-deps:micro-deps:compileGroovy UP-TO-DATE
:micro-deps:micro-deps:processResources UP-TO-DATE
:micro-deps:micro-deps:classes UP-TO-DATE
:micro-deps:micro-deps:jar UP-TO-DATE
:stub-runner:stub-runner:compileJava UP-TO-DATE
:stub-runner:stub-runner:compileGroovy UP-TO-DATE
:stub-runner:stub-runner:classes UP-TO-DATE
:stub-runner:stub-runner:jar UP-TO-DATE
:stub-runner:stub-runner:startScripts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':stub-runner:stub-runner:startScripts'.
> No value has been specified for property 'mainClassName'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.979 secs
```

**Comment by marcingrzejszczak** [comment] 2015-06-18 14:47
you should use `./gradlew publishToMavenLocal`

**Comment by ArturGajowy** [comment] 2015-06-18 14:57
yeah, that's what @szpak said :) He asked me to create this ticket (I think did so because if there is a task available in the gradle project, it should work ;>)

**Comment by szpak** [comment] 2015-06-18 16:49
Old maven plugin can be probably completely removed to not mislead users.

**Comment by marcingrzejszczak** [comment] 2015-11-15 11:39
Duplicate of https://github.com/4finance/micro-infra-spring/issues/513

**Closed by marcingrzejszczak** 2015-11-15 11:39 UTC
